<a href="https://colab.research.google.com/github/PedroAfonsoBraga/PyTorch_fundamentals/blob/main/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Importando bibliotecas

In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.0.1+cu118


# **Criando Tensores**

Tensores do PyTorch são criados com `torch.tensor()`
https://pytorch.org/docs/stable/tensors.html#torch.Tensor


Escalar

In [4]:
#Escalar
scalar = torch.tensor(7)
scalar

tensor(7)

não tem dimensões, é apenas um único número

In [5]:
#n. de dimensoes
scalar.ndim

0

In [6]:
# Retorna o item do scalar
scalar.item()

7

Vetor

In [7]:
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [10]:
# numero de dimensoes (n. de [])
vector.ndim

1

In [11]:
# shape do vetor
vector.shape

torch.Size([2])

MATRIZ

In [12]:
MATRIX = torch.tensor([[1,2],
                       [3,4]])
MATRIX

tensor([[1, 2],
        [3, 4]])

In [13]:
MATRIX.ndim

2

In [16]:
MATRIX[1]

tensor([3, 4])

In [17]:
MATRIX.shape

torch.Size([2, 2])

Tensor

In [29]:
TENSOR = torch.tensor([[[1,2,3],
                        [3,6,9],
                        [2,4,5]],
                       [[1,3,5],
                        [7,8,9],
                        [9,7,5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]],

        [[1, 3, 5],
         [7, 8, 9],
         [9, 7, 5]]])

In [30]:
TENSOR.ndim

3

In [31]:
TENSOR.shape

torch.Size([2, 3, 3])

In [34]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

# **Criando Tensores aleatórios**

**Por que tensores aleatórios?**

Tensores aleatórios são importantes porque é a maneira como muitas redes neurais aprendem, começando com tensores com valores aleatórios, e então ajustam estes valores para melhor representar os dados

`Inicia com números aleatórios -> observa os dados -> atualiza valores aleatórios -> observa os dados -> atualiza valores aleatórios`

**Criando Tensor aleatório**

Tensor de tamanho (3,4)

Torch docs - https://pytorch.org/docs/stable/generated/torch.rand.html#torch.rand

In [3]:
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.4125, 0.5180, 0.8894, 0.6679],
        [0.5299, 0.3737, 0.1165, 0.2661],
        [0.9328, 0.0975, 0.1742, 0.7616]])

In [4]:
random_tensor.ndim

2