<a href="https://colab.research.google.com/github/PedroAfonsoBraga/PyTorch_fundamentals/blob/main/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Importando bibliotecas**

In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.2.1+cu121


# **Criando Tensores**

Tensores do PyTorch são criados com `torch.tensor()`
https://pytorch.org/docs/stable/tensors.html#torch.Tensor


**Escalar**

In [ ]:
#Escalar
scalar = torch.tensor(7)
scalar

tensor(7)

não tem dimensões, é apenas um único número

In [ ]:
#n. de dimensoes
scalar.ndim

0

In [ ]:
# Retorna o item do scalar
scalar.item()

7

**Vetor**

In [ ]:
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [ ]:
# numero de dimensoes (n. de [])
vector.ndim

1

In [ ]:
# shape do vetor
vector.shape

torch.Size([2])

**Matriz**

In [ ]:
MATRIX = torch.tensor([[1,2],
                       [3,4]])
MATRIX

tensor([[1, 2],
        [3, 4]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX[1]

tensor([3, 4])

In [ ]:
MATRIX.shape

torch.Size([2, 2])

**Tensor**

In [ ]:
TENSOR = torch.tensor([[[1,2,3],
                        [3,6,9],
                        [2,4,5]],
                       [[1,3,5],
                        [7,8,9],
                        [9,7,5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]],

        [[1, 3, 5],
         [7, 8, 9],
         [9, 7, 5]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([2, 3, 3])

In [ ]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

# **Criando Tensores aleatórios**

**Por que tensores aleatórios?**

Tensores aleatórios são importantes porque é a maneira como muitas redes neurais aprendem, começando com tensores com valores aleatórios, e então ajustam estes valores para melhor representar os dados

`Inicia com números aleatórios -> observa os dados -> atualiza valores aleatórios -> observa os dados -> atualiza valores aleatórios`

**Criando Tensor aleatório**

Tensor de tamanho (3,4)

Torch docs - https://pytorch.org/docs/stable/generated/torch.rand.html#torch.rand

In [ ]:
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.6390, 0.9682, 0.6035, 0.9533],
        [0.2711, 0.5503, 0.4643, 0.2067],
        [0.0935, 0.1136, 0.1464, 0.8171]])

In [ ]:
random_tensor.ndim

2

**Criando um tensor aleatório com um shape similar a uma imagem**

In [ ]:
random_image_size_tensor = torch.rand(size = (224, 224, 3))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

**Zeros e uns**

In [ ]:
# zeros
zeros = torch.zeros(3,4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
# um
uns = torch.ones(3,4)
uns

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
uns.dtype

torch.float32

# **Criando um range de tensores e similares**

Usando torch.arange()

In [ ]:
um_a_dez = torch.arange(1,11)
um_a_dez

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
# Criando um tensor similiar
dez_zeros = torch.zeros_like(um_a_dez)
dez_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

#**Tipo de dados em Tensores**

**Float 32 tensor**

Mesmo com dtype em None, por padrão o tensor criiado é float32. Definindo outro tipo, altera-se.
https://pytorch.org/docs/stable/tensors.html#data-types

**note**: Tensor datatypes são os erros mais comuns que serão enfrentados com PyTorch e deep learning:
1. Tensor não está como o datatype correto
2. Tensor não está com o shape correto
3. Tensor não está com o device correto


In [ ]:
float_32_tensor = torch.tensor([3., 6., 9.],
                               dtype = None, #tipo de dado do tensor (float32 ou float 16)
                               device=None, #em qual device está o tensor
                               requires_grad=False) #se o tensor está com gradientes em operações

float_32_tensor

tensor([3., 6., 9.])

In [ ]:
float_32_tensor.dtype

torch.float32

In [ ]:
#alterando datatype
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [ ]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

**32 integer tensor**

In [ ]:
int_32_tensor = torch.tensor([3,6,8], dtype=torch.int32)
int_32_tensor

tensor([3, 6, 8], dtype=torch.int32)

In [ ]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 72.])

# **Adquirindo e manipulando informações de tensores (Tensor Attributes)**
1. Tensor não está como o datatype correto - para adquirir datatype de um tensor, use `tensor.dtype`
2. Tensor não está com o shape correto - para adquirir o shape de um tensor, use `tensor.shape` ou `tensor.size`
3. Tensor não está com o device correto - para adquirir o device de um tensor, use `tensor.device`

In [ ]:
algum_tensor = torch.rand(3,4)
algum_tensor

tensor([[9.8409e-01, 6.7456e-01, 1.9847e-01, 1.5086e-01],
        [5.9807e-01, 5.0742e-02, 6.6822e-01, 7.3889e-01],
        [1.4879e-01, 4.0581e-01, 8.3613e-04, 8.6930e-01]])

**Verificando detalhes de um tensor**

In [ ]:
print(algum_tensor)
print()
print(f"Datatype do tensor: {algum_tensor.dtype}")
print(f"Shape do tensor: {algum_tensor.shape}")
print(f"Device do tensor: {algum_tensor.device}")

tensor([[9.8409e-01, 6.7456e-01, 1.9847e-01, 1.5086e-01],
        [5.9807e-01, 5.0742e-02, 6.6822e-01, 7.3889e-01],
        [1.4879e-01, 4.0581e-01, 8.3613e-04, 8.6930e-01]])

Datatype do tensor: torch.float32
Shape do tensor: torch.Size([3, 4])
Device do tensor: cpu


# **Manipulando tensores**

Operações com tensores incluem:
* Adição
* Subtração
* Multiplicação (***element-wise***)
* Divisão
* Multiplicação de **matriz**

In [ ]:
# Criando um tensor
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [ ]:
# Multiplicando por 10
tensor * 10


tensor([10, 20, 30])

In [ ]:
tensor # note: não é substituído

tensor([1, 2, 3])

In [ ]:
# Subtrair
tensor - 10

tensor([-9, -8, -7])

**in-built functions**


In [ ]:
torch.mul(tensor, 10) #dê preferência aos operadores em python
torch.add(tensor, 10)

tensor([11, 12, 13])

**Multiplicação de matrizes**

Existem duas principais formas de multiplicação em neural networks e deep learning:

* Element-wise
* Multiplicação de matrizes (*dot product*) [ https://www.mathsisfun.com/algebra/matrix-multiplying.html ]

Obs: Existem duas regras principais sobre a multiplicação de matrizes que precisam ser satisfeitas:
  1. As dimensões precisam combinar:

    `(3, 2) @ (3, 2) - não funciona`

    `(2, 3) @ (3, 2) - funciona`
  2. A matriz resultante tem o shape da dimensão exterior


In [ ]:
# Element-wise
print(tensor, "*", tensor)
print(f"Igual a: {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Igual a: tensor([1, 4, 9])


In [ ]:
# Matrix Multiplication (dot product)
torch.matmul(tensor, tensor)

tensor(14)

in-built function é mais eficaz, nesse caso

In [ ]:
# um por um
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: user 678 µs, sys: 0 ns, total: 678 µs
Wall time: 686 µs


In [ ]:
#in built function
%%time
torch.matmul(tensor, tensor)

CPU times: user 71 µs, sys: 6 µs, total: 77 µs
Wall time: 81.3 µs


tensor(14)

obs: atenção ao shape error

**Operação *transpose***

In [ ]:
tensorA = torch.tensor([[1, 2],
                       [3, 4],
                       [5, 6]])
tensorB = torch.tensor([[7, 10],
                        [8, 11],
                        [9, 12]])

Nesta situação, operações não podem ser feitas. As dimensões não correspondem (3x2 @ 3x2). Para corrigir, aplicamos uma transposição em um dos tensores, de modo que seja compatível (3x2 @ 2x3)

In [ ]:
print(tensorB)
print()
tensorB.T

tensor([[ 7, 10],
        [ 8, 11],
        [ 9, 12]])



tensor([[ 7,  8,  9],
        [10, 11, 12]])

Dessa forma conseguimos realizar operações

In [ ]:
torch.matmul(tensorA, tensorB.T)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

# **Tensor Aggregation**

Encontrando mínimo, máximo, mean, soma, etc

In [ ]:
# Criando tensor
x = torch.arange(0, 100,10)
x
x.dtype

torch.int64

In [ ]:
torch.min(x), x.min()

(tensor(0), tensor(0))

In [ ]:
torch.max(x), x.max()

(tensor(90), tensor(90))

In [ ]:
torch.mean(x)
# datatype incorreto - mean requer datatype float 32

RuntimeError: mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long

In [ ]:
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [ ]:
torch.sum(x), x.sum()

(tensor(450), tensor(450))

Encontrando o positional min and max

In [ ]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
# find the position in tensor that has the minimum value with argmin() ->
# returns index position of target tensr where the minimum value occurs
x.argmin()

tensor(0)

In [ ]:
# the same with argmax()
x.argmax()

tensor(9)